name: monitoring
services:
  http-server:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db-server
  db-server:
    build: 
      context: ./mongo
      secrets:
        - mongo_username
        - mongo_password
    restart: always
    ports:
      - 27017:27017
secrets:
  mongo_username:
    file: ./mongo/secrets/mongo_username.txt
  mongo_password:
    file: ./mongo/secrets/mongo_password.txt