set PROJECT_DIR=%~dp0\..
set STANDALONE_DIR=%PROJECT_DIR%\.next\standalone
set STATIC_DIR=%PROJECT_DIR%\.next\static
set PUBLIC_DIR=%PROJECT_DIR%\public
set INSTALLER_DIR=%~dp0\monitoring
set STANDALONE_INSTALLER_DIR=%INSTALLER_DIR%\standalone
set STATIC_INSTALLER_DIR=%STANDALONE_INSTALLER_DIR%\.next\standalone
set PUBLIC_INSTALLER_DIR=%STANDALONE_INSTALLER_DIR%\public

rmdir "%STANDALONE_INSTALLER_DIR%" /s /q

xcopy "%STANDALONE_DIR%\*" "%STANDALONE_INSTALLER_DIR%" /i /s /e /k /h /o /x